//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.04 at 01:53:55 PM CET 
//

@javax.xml.bind.annotation.XmlSchema (namespace = "mise.marssa.footprint.datatypes.decimal.electrical.current")
package mise.marssa.footprint.datatypes.decimal.electrical.current;

